/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abercompany_bakonproto_ndk_NDK */

#ifndef _Included_com_abercompany_bakonproto_ndk_NDK
#define _Included_com_abercompany_bakonproto_ndk_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abercompany_bakonproto_ndk_NDK
 * Method:    run_ffmpeg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_abercompany_bakonproto_ndk_NDK_run_1ffmpeg
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
